version: "3.9"
services:
  docker-saigneur-utilisateur:
    image: saigneur-utilisateur
    container_name: msaigneur-utilisateur
    build:
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    restart: always
    depends_on:
      - docker-saigneur-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://docker-saigneur-postgres:5432/saigneurutilisateurdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: adminpostgres
    networks:
      - saigneur-network

networks:
  saigneur-network:
    external: true
